#!/bin/bash

coverage=`cat _rel/log/cover/total/index.html | grep '^<tr><th>' | sed 's/<[\/a-z]*><[\/a-z]*>/ /g' | sed 's/%//' | sed '$d'`

thresholds_file=$1
pass=0

while read -r line; do
    set $line > /dev/null
    app_name=$1
    current_coverage=$2
    limit=`grep $app_name $thresholds_file`
    set $limit > /dev/null
    expected_coverage=$2
    if [ "$current_coverage" -ge "$expected_coverage" ]; then
        echo "$(tput setaf 2)Coverage above threshold:$(tput sgr0) $app_name"
        echo "Expected coverage: $expected_coverage%"
        echo "Current coverage: $current_coverage%"
        echo ""
    else
        echo "$(tput setaf 1)Coverage below threshold:$(tput sgr0) $app_name"
        echo "Expected coverage: $expected_coverage%"
        echo "Current coverage: $current_coverage%"
        pass=1
    fi
done < <(echo "$coverage")

exit $pass
